# config deterministica melonDS DSi (usata da mrun2.sh via XDG_CONFIG_HOME=/tmp/mdscfg)
RecentROM = [""]
AudioSync = false
LimitFPS = true

[DLDI]
Enable = false

[Console]
ConsoleType = 1

[Firmware]
Path = "/home/lardx/sgnds/DS firmware + DSi NAND and firmware/dsfirmware.bin"

[DSi]
ExternalBIOSEnable = true
BIOS9Path = "/home/lardx/sgnds/DS firmware + DSi NAND and firmware/biosdsi9.bin"
BIOS7Path = "/home/lardx/sgnds/DS firmware + DSi NAND and firmware/biosdsi7.bin"
FirmwarePath = "/home/lardx/sgnds/DS firmware + DSi NAND and firmware/dsifirmware.bin"
NANDPath = "/home/lardx/sgnds/DS firmware + DSi NAND and firmware/dsinand.bin"

[3D]
Renderer = 0

[3D.Soft]
Threaded = true

[Audio]
Interpolation = 0
BitDepth = 0

[MP]
AudioMode = 1
RecvTimeout = 25
