#!/usr/bin/env python3
"""Extract Sonic Generations 3DS Green Hill Act 1 collision from the RomFS dump.

Input:  z11coll.bin (from TARGET.cpk -> amb/Z11_MAP, unpacked by AMBextract)
Format (reverse engineered from data): float32 stream after a 4-byte header.
Each surface segment is:
    P1(x,y,z) | sin(angle) cos(angle) | pad | P2(x,y,z)
A unit (sin,cos) pair is the signature; P1 sits 3 floats before it, P2 three
floats after the pad. Chained segments share endpoints (curved hills are
approximated by short segments with increasing angles - the classic GHZ 2:1
slope shows up as 26.57 deg).

Output: z11_coll.json (segments) and z11_coll.h (C array for the DS engine,
fixed-point f12; y is flipped to screen-down for the DS 2.5D view).
"""
import struct, json, math, sys

def extract(path):
    b = open(path, 'rb').read()
    n = (len(b) - 4) // 4
    f = struct.unpack_from('<%df' % n, b, 4)
    def unit(a, c): return 0.985 < a*a + c*c < 1.015
    segs, seen = [], set()
    for i in range(3, n - 5):
        if unit(f[i], f[i+1]):
            p1 = (round(f[i-3],3), round(f[i-2],3), round(f[i-1],3))
            p2 = (round(f[i+3],3), round(f[i+2],3), round(f[i+1],3))
            key = (p1, p2)
            if key in seen or p1 == p2: continue
            deg = math.degrees(math.atan2(f[i], f[i+1]))
            # physics check: the stored angle must match the P1->P2 slope
            dx, dy = p2[0]-p1[0], p2[1]-p1[1]
            if dx*dx + dy*dy < 1e-6: continue
            slope = math.degrees(math.atan2(dy, dx))
            if abs(abs(slope) - abs(deg)) > 2.5 and abs(abs(slope)-180-abs(deg)) > 2.5: continue
            seen.add(key)
            segs.append({'p1': p1, 'p2': p2,
                         'deg': round(deg, 2),
                         'z': round(p1[2], 1)})
    return segs

def to_c(segs, fname):
    F = 1 << 12   # 12-bit fixed point for the DS engine
    lines = [
        '/* Generated by tools/z11_extract.py - Sonic Generations 3DS GHZ Act1',
        ' * collision segments (%d). Coordinates: 3DS world units, x right,' % len(segs),
        ' * y UP. Convert to DS screen space in engine. */',
        '#ifndef Z11_COLL_H',
        '#define Z11_COLL_H',
        'typedef struct { short x1,y1,x2,y2; short z; short deg8; } CollSeg;',
        'static const CollSeg z11_coll[%d] = {' % len(segs),
    ]
    for s in segs:
        lines.append('  {%5d,%5d,%5d,%5d,%5d,%4d},' % (
            round(s['p1'][0]*F), round(s['p1'][1]*F),
            round(s['p2'][0]*F), round(s['p2'][1]*F),
            round(s['z']*F), round(s['deg']*8)))
    lines += ['};', '#endif', '']
    open(fname, 'w').write('\n'.join(lines))

if __name__ == '__main__':
    src = sys.argv[1] if len(sys.argv) > 1 else 'z11coll.bin'
    segs = extract(src)
    json.dump(segs, open('z11_coll.json', 'w'))
    to_c(segs, 'z11_coll.h')
    print('%d segments -> z11_coll.json / z11_coll.h' % len(segs))
